In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

# 랜덤한 [40,4] 크기의 dataset 생성
dataset = np.random.random([40,4]) 

# 1. dataset의 0번부터 2번 column 인덱스까지의 배열을 feature로 저장합니다.
feature = dataset[:,:3]
# 2. dataset의 마지막 column 인덱스의 column 벡터를 label로 저장합니다.
label = dataset[:,-1]

print(feature, feature.shape) #40,3
print(label, label.shape) #40,

[[0.79211379 0.35634382 0.37483894]
 [0.4626749  0.52203705 0.38400656]
 [0.79319508 0.72681727 0.48683832]
 [0.92366216 0.0964799  0.87597742]
 [0.36364499 0.28874085 0.80356184]
 [0.95828734 0.79061922 0.11789047]
 [0.48671499 0.96679234 0.49182904]
 [0.62406723 0.9265309  0.9411213 ]
 [0.32699222 0.03696636 0.9714859 ]
 [0.63526741 0.02450422 0.16932897]
 [0.76569024 0.72570785 0.15525492]
 [0.46839877 0.58214822 0.27649133]
 [0.09616726 0.58044367 0.04356475]
 [0.98753146 0.06597794 0.54029077]
 [0.55589236 0.00756584 0.05176549]
 [0.1045426  0.84909151 0.76070509]
 [0.92645285 0.28965314 0.82050345]
 [0.36410704 0.94768542 0.52990813]
 [0.79841296 0.67873465 0.43858135]
 [0.82348134 0.00793454 0.18793654]
 [0.22645276 0.71499609 0.61116234]
 [0.02189418 0.66580712 0.14076678]
 [0.05028964 0.02431606 0.76494132]
 [0.78658545 0.90926337 0.80476923]
 [0.16276942 0.81905724 0.51363611]
 [0.40500383 0.35533087 0.94032455]
 [0.7150688  0.169567   0.91903852]
 [0.4916647  0.43853927 0.66

In [ ]:
# 전체 데이터를 학습 데이터와 검증 데이터로 나눕니다.
# 3. 테스트용 데이터의 크기를 0.25로 하여 전체 데이터를 분리합니다.random_state는 121을 입력합니다.
X_train, X_test, Y_train, Y_test = train_test_split(feature, label, test_size=0.25, random_state=121)

# 분리된 데이터의 크기들을 출력
print("Case 1.")
print("X_train shape : {}".format(X_train.shape)) #30, 3
print("X_test shape : {}".format(X_test.shape)) #10, 3
print("Y_train shape : {}".format(Y_train.shape)) #30,
print("Y_test shape : {}".format(Y_test.shape)) #10, 

Case 1.
X_train shape : (30, 3)
X_test shape : (10, 3)
Y_train shape : (30,)
Y_test shape : (10,)


In [ ]:
# 4. shuffle을 하지 않고 test_size를 0.3으로 하여 학습용 데이터와 테스트용 데이터를 분리합니다. random_state는 121을 입력합니다.
X_train_2, X_test_2, Y_train_2, Y_test_2 = train_test_split(feature, label, test_size=0.3, random_state=121, shuffle=False)

# 분리된 데이터의 크기들을 출력
print("\nCase 2.")
print("X_train_2 shape : {}".format(X_train_2.shape))  #28,3
print("X_test_2 shape : {}".format(X_test_2.shape)) #12, 3
print("Y_train_2 shape : {}".format(Y_train_2.shape)) #28,
print("Y_test_2 shape : {}".format(Y_test_2.shape)) #12,



Case 2.
X_train_2 shape : (28, 3)
X_test_2 shape : (12, 3)
Y_train_2 shape : (28,)
Y_test_2 shape : (12,)
